<?php

namespace Aurelio\AgendaBundle\Repository;

/**
 * ReuniaoDiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReuniaoDiaRepository extends \Doctrine\ORM\EntityRepository
{
}
