<?php

namespace Aurelio\AgendaBundle\Repository;

/**
 * ReuniaoStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReuniaoStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
