<?php

namespace Aurelio\AgendaBundle\Repository;

/**
 * ReuniaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReuniaoRepository extends \Doctrine\ORM\EntityRepository
{
}
