<?php

namespace Aurelio\AgendaBundle\Repository;

/**
 * ReuniaoPessoaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReuniaoPessoaRepository extends \Doctrine\ORM\EntityRepository
{
}
